"""Settings loader with defaults merge."""

import json
from typing import Any

DEFAULTS: dict[str, Any] = {
    "assistant_name": "Jarvis",
    "voice_first_only": True,
    "safe_mode": False,
    "python_required_major": 3,
    "python_required_minor": 11,
    "llm_model": "qwen3.5:4b",
    "llm_base_url": "http://localhost:11434",
    "llm_keep_alive": "10m",
    "llm_timeout_seconds": 18,
    "llm_max_tool_rounds": 2,
    "llm_temperature": 0.05,
    "llm_num_ctx": 4096,
    "llm_num_predict": 128,
    "ollama_use_python_client": True,
    "ollama_auto_recover": True,
    "stt_model": "large-v3-turbo",
    "stt_fallback_models": ["large-v3", "medium"],
    "stt_device_preference": "cuda",
    "stt_gpu_compute_types": ["int8_float16", "float16"],
    "stt_cpu_compute_type": "int8",
    "stt_cpu_threads": 4,
    "stt_num_workers": 1,
    "stt_language": "en",
    "stt_beam_size": 10,
    "stt_best_of": 5,
    "stt_patience": 2.0,
    "stt_repetition_penalty": 1.1,
    "stt_no_repeat_ngram_size": 3,
    "stt_temperature": 0,
    "stt_temperature_fallback": [0.0, 0.2, 0.4, 0.6],
    "stt_condition_on_previous_text": False,
    "stt_initial_prompt": "Voice commands to play songs. Song titles and artist names.",
    "stt_hotwords_from_vocabulary": True,
    "stt_vad_filter": True,
    "stt_no_speech_threshold": 0.6,
    "stt_log_prob_threshold": -1.0,
    "stt_compression_ratio_threshold": 2.2,
    "wake_word_model": "hey_jarvis",
    "wake_microphone_device_id": 0,
    "command_microphone_device_id": 0,
    "wake_word_threshold": 0.2,
    "wake_ack_enabled": True,
    "wake_ack_blocking": True,
    "post_wake_delay_seconds": 0.5,
    "vad_pre_roll_seconds": 0.6,
    "vad_min_record_seconds": 0.8,
    "vad_max_record_seconds": 10,
    "vad_silence_duration_seconds": 1.0,
    "vad_start_threshold": 500,
    "vad_stop_threshold": 300,
    "minimum_audio_volume": 350,
    "stt_speech_start_timeout_seconds": 8.0,
    "stt_pause_media_during_capture": True,
    "tts_engine": "pyttsx3",
    "tts_fallback_engine": "pyttsx3",
    "tts_voice": "am_michael",
    "tts_speed": 1.0,
    "tts_sample_rate": 24000,
    "tts_non_blocking": True,
    "tts_enabled": True,
    "fuzzy_high_confidence": 92,
    "fuzzy_medium_confidence": 65,
    "voice_confirmation_enabled": True,
    "confirmation_max_attempts": 2,
    "youtube_search_results": 15,
    "youtube_auto_play_threshold": 82,
    "youtube_confirm_threshold": 65,
    "youtube_reject_threshold": 55,
    "music_auto_play_confidence": 0.85,
    "music_confirm_confidence": 0.65,
    "music_enrichment_enabled": True,
    "music_enrichment_auto_threshold": 65,
    "music_corrections_cache_path": "config/music_corrections_cache.json",
    "music_entity_cache_path": "config/music_entity_cache.json",
    "music_vocabulary_path": "config/music_vocabulary.json",
    "music_entity_lookup_enabled": True,
    "music_entity_cache_enabled": True,
    "musicbrainz_enabled": True,
    "wikidata_enabled": True,
    "google_dym_enabled": False,
    "google_dym_timeout_seconds": 5,
    "google_dym_min_delay_seconds": 2,
    "google_dym_max_delay_seconds": 4,
    "musicbrainz_rate_limit_seconds": 1.1,
    "wikidata_rate_limit_seconds": 1.1,
    "entity_lookup_timeout_seconds": 5,
    "entity_lookup_user_agent": "Jarvis3.0/1.0 (local personal assistant)",
    "workflows_dir": "config/workflows",
    "allowed_apps_path": "config/allowed_apps.json",
    "browse_enabled": True,
    "browse_headless": True,
    "browse_timeout_ms": 25000,
    "browse_max_text_chars": 6000,
    "intent_resolution_enabled": True,
    "intent_resolution_min_confidence": "medium",
    "intent_resolver_timeout_seconds": 20,
    "intent_resolver_num_predict": 160,
    "layer_pipeline_enabled": True,
    "layer_progressive_tts": True,
    "layer0_search_enabled": True,
    "layer0_search_engines": ["google", "bing", "yahoo"],
    "layer0_search_wait_ms": 1500,
    "layer0_lite_timeout_seconds": 8,
    "layer0_cache_max_entries": 200,
    "layer0_cache_ttl_seconds": 86400,
    "layer1_intent_enabled": True,
    "layer1_max_context_chars": 4000,
    "google_ai_search_enabled": False,
    "google_ai_wait_ms": 2000,
}


def load_settings(config_path: str = "config/settings.json") -> dict[str, Any]:
    merged = dict(DEFAULTS)
    for path in (config_path, "config/settings.local.json"):
        try:
            with open(path, "r", encoding="utf-8") as f:
                file_settings = json.load(f)
            if isinstance(file_settings, dict):
                merged.update(file_settings)
        except (FileNotFoundError, json.JSONDecodeError, OSError):
            pass
    return merged
